name: Add new icon
description: Add a new icon to the icon library
title: "Add new icon"
labels: ["new-icon"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting new icons for the icon library! Please fill out the following information to update the icon library.
  - type: input
    id: name
    attributes:
      label: Name
      description: This is just a simple one or two word name for the icon
      placeholder: ex. 'Arrow down'
      value: 'Bulb'
    validations:
      required: true
  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: Please list any keywords that describe the icon. This will help people find the icon in the library. Comma separated.
      placeholder: arrow, down, direction
      value: 'light, solution, idea, bulb'
    validations:
      required: true
  - type: textarea
    id: svg
    attributes:
      label: SVG
      description: Please copy and paste the SVG code for the icon. Don't worry about format, we take care of that.
      placeholder: | 
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='5' x2='12' y2='19'></line><polyline points='19 12 12 19 5 12'></polyline></svg>"
      value: |
        <svg xmlns='http://www.w3.org/2000/svg' width='64' height='64' fill='none'><path stroke='#21bca5' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' d='M32.01 3.01v7.56m-21.39 1.3 5.35 5.35m37.43-5.35-5.34 5.35M3.03 33.26h7.56m50.41 0h-7.56'/><path fill='#21bca5' fill-rule='evenodd' d='M40 46.37a16 16 0 1 0-16 0v6.13a8 8 0 1 0 16 0v-6.13z' clip-rule='evenodd' opacity='.4'/></svg>
    validations:
      required: true