name: Add new icon
description: Add a new icon to the icon library
title: "Add new icon"
labels: ["new-icon"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting new icons for the icon library! Please fill out the following information to update the icon library.
  - type: input
    id: name
    attributes:
      label: Name
      description: This is just a simple one or two word name for the icon
      placeholder: ex. 'Arrow down'
    validations:
      required: true
  - type: textarea
    id: svg
    attributes:
      label: SVG
      description: Please copy and paste the SVG code for the icon. Don't worry about format, we take care of that.
      placeholder: | 
        ```html
        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='5' x2='12' y2='19'></line><polyline points='19 12 12 19 5 12'></polyline></svg>
        ```
      value: |
        ```html
        YOUR SVG CODE HERE
        ```
    validations:
      required: true